apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/podinfo
  - ../base/rancher
patches:
  - path: podinfo-values.yaml
    target:
      kind: HelmRelease
  - path: rancher-values.yaml
    target:
      kind: HelmRelease
