---
device_name: Basement AP
device_hostname: acpro01
device_fqdn: acpro01.addeo.net
device_ip: 10.1.10.38
device_type: Unifi Access Point # @TODO not accurate
device_model: AC Pro # @TODO not accurate
device_mac: 78:8A:20:86:5B:B1
