---
# Device Information.
device_name: Upstairs Beacon
device_hostname: beacon02
device_type: Unifi BeaconHD WiFi Extender
device_model: UAP-BeaconHD
device_vlan: MGMT
device_interfaces:
  - ip: 10.1.10.114 # @TODO use static ip
    mac: D0:21:F9:72:A0:00
    default: true
