---
# Server Configuration.
server_hostname: cantilever
server_fqdn: cantilever.addeo.net

# DNS Record Configuration.
dns_records:
  - host: cantilever
    domain: addeo.net
    ip: 10.1.15.66
    descr: "Proxmox Server: cantilever"
    aliases:
      - host: vmm01.prd.ado
        domain: addeo.net
        description: vmm01.prd.ado
  - host: cantilever.mgmt
    domain: addeo.net
    ip: 10.1.10.16
    descr: "iDrac: cantilever"

# Bootstrap Configuration.
bootstrap_boot_type: uefi
bootstrap_iscsi_boot: true
bootstrap_iscsi_interface_name: eno1
bootstrap_iscsi_initiator: iqn.2020-08.net.addeo:cantilever
# @TODO add netmask setting.
bootstrap_iscsi_initiator_ip: 172.16.0.66
bootstrap_iscsi_target_name: iqn.2020-08.net.addeo:kilo:spool-iscsi-cantilever
bootstrap_iscsi_target_ip: 172.16.0.65
bootstrap_zpool_encrypt_root: false
bootstrap_zpool_type: single
bootstrap_zpool_disk_identifiers:
  - /dev/disk/by-path/ip-172.16.0.65:3260-iscsi-iqn.2020-08.net.addeo:kilo:spool-iscsi-cantilever-lun-1

# Network Interfaces Configuration.
network_interfaces:
  eno1:
    comment: iSCSI boot interface.
    auto: true
    no_auto_down: true
    inet: static
    address: 172.16.0.66/29
    mtu: 9000
    pre_up: /usr/sbin/ip link set eno1 mtu 9000
    state: present
  eno2:
    inet: manual
    state: present
  eno3:
    comment: SRVMGMT interface.
    inet: manual
    state: present
  eno4:
    inet: manual
    state: present
  enp4s0:
    comment: SAN interface.
    auto: true
    inet: manual
    mtu: 9000
    state: present
  vmbr0:
    auto: true
    inet: manual
    extra: |
      bridge-ports eno3
      bridge-stp off
      bridge-fd 0
      bridge-vlan-aware yes
      bridge-vids 2-4094
    state: present
  vmbr0.115:
    comment: SRVMGMT Network.
    auto: true
    inet: static
    address: 10.1.15.66/24
    gateway: 10.1.15.1
    dns_nameservers: 10.1.15.1
    state: present
  vmbr1:
    comment: SAN bridge.
    auto: true
    inet: static
    address: 10.1.12.66/24
    gateway: 10.1.12.1
    mtu: 9000
    extra: |
      bridge-ports enp4s0
      bridge-stp off
      bridge-fd 0
      up ip route add 10.1.15.79 dev vmbr1
      down ip route del 10.1.15.79 dev vmbr1
    state: present

# ZFS Configuration.
zfs_pools:
  bpool:
    scrub: false
    state: scrub
  rpool:
    scrub: weekly
    state: scrub
  vmpool:
    vdevs:
      - type: mirror
        devices:
          - /dev/disk/by-id/ata-ADATA_SP550_2F4920016280
          - /dev/disk/by-id/ata-KINGSTON_SA400S37240G_50026B778345A773
    scrub: weekly
    properties:
      ashift: 12
    filesystem_properties:
      compression: lz4
      relatime: "on"
      xattr: sa
      utf8only: "on"
    state: present

# Proxmox Configuration.
# @TODO encryption?
pve_storages:
  - name: local-vmpool
    type: zfspool
    content:
      - images
      - rootdir
    pool: vmpool
  - name: bruce
    type: pbs
    content:
      - backup
    server: 10.1.15.79
    username: backup@pbs
    password: "{{ (hostvars['bruce.addeo.net']['pbs_users'] | selectattr('username', 'eq', 'backup@pbs'))[0].password }}"
    datastore: kilo
    fingerprint: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      66303962393831623637643634353839633862313862396232646461376432326437656135613539
      6161383762333932656466383633623464656462396366650a343164396637343964353937326363
      62346436326138666531343338383834653561316133376330336665306565396262643161343936
      3533333535636639650a383036353636643033333136353561313838333363393631393263313636
      64666634333033396233346362643263663531386339396332326238613338656135363466663232
      66306331663037653963356139383561353932366162393137363562626337643962626336333532
      31623063663862356432653764323136323464353334623563386234306233656364373133383537
      65306536393439336531626535376538653166336231306565313565373930353036653839386463
      3162
