---
# @todo the ip/default settings on eth1 seem odd here.
device_hostname: edge
device_type: Ubiquiti EdgeRouter X
device_model: ER-X
device_interfaces:
  - name: eth0
    mac: D0:21:F9:49:37:80
  - name: eth1
    ip: 172.16.10.1
    mac: D0:21:F9:49:37:81
    default: true
  - name: eth2
    mac: D0:21:F9:49:37:82
  - name: eth2
    mac: D0:21:F9:49:37:83
  - name: eth3
    mac: D0:21:F9:49:37:84
  - name: switch0
    mac: D0:21:F9:49:37:85

# DNS Record Configuration.
dns_records:
  - host: edge
    domain: addeo.net
    ip: 172.16.10.1
    descr: Edge Router
    aliases:
      - host: edge.prd.ado
        domain: addeo.net
        description: edge.prd.ado
