---
# Device Information.
device_name: Office IWAP
device_hostname: iwhd02
device_type: Unifi In-Wall HD Access Point
device_model: UAP-IW-HD
device_vlan: MGMT
device_interfaces:
  - ip: 10.1.10.109 # @TODO use static ip
    mac: 78:45:58:D6:F2:7C
    default: true
