---
# Server Configuration.
server_hostname: kilo
server_fqdn: kilo.addeo.net
kilo_server_users__to_merge:
  - name: spool
    password_lock: true
    create_home: false
    shell: /usr/bin/false
  - name: ansible
    groups:
      - spool

# Bootstrap Configuration.
bootstrap_zpool_encrypt_root: true
bootstrap_zpool_type: mirror
bootstrap_zpool_disk_identifiers:
  - /dev/disk/by-id/scsi-3500a0751e5a956ff
  - /dev/disk/by-id/scsi-3500a0751e5a9496e

# Network Interfaces Configuration.
network_interfaces:
  # iSCSI boot for cantilever.
  eno1:
    auto: true
    no_auto_down: true
    inet: static
    address: 172.16.0.65/29
    mtu: 9000
    state: present
  # SAN for crimson.
  eno2:
    auto: true
    inet: static
    address: 172.16.2.65/24
    mtu: 9000
    state: present
  # SRVMGMT network.
  eno3:
    auto: true
    inet: static
    address: 10.1.15.65/24
    gateway: 10.1.15.1
    dns_nameservers: 10.1.15.1
    state: present
  # SAN for cantilever.
  enp65s0:
    auto: true
    inet: static
    address: 172.16.1.65/24
    mtu: 9000
    state: present

# Firewall Configuration.
kilo_firewall_allowed_udp_ports__to_merge:
  - 137 # SMB
  - 138 # SMB
  - 2049 # NFS
kilo_firewall_allowed_tcp_ports__to_merge:
  - 139 # SMB
  - 445 # SMB
  - 2049 # NFS
  - 3260 # iSCSI

# ZFS Configuration.
zfs_pools:
  bpool:
    scrub: false
    state: scrub
  rpool:
    scrub: weekly
    state: scrub
  spool:
    vdevs:
      - type: raidz2
        devices:
          - /dev/disk/by-id/wwn-0x5000cca267c7fe1f
          - /dev/disk/by-id/wwn-0x5000cca267c8344e
          - /dev/disk/by-id/wwn-0x5000cca26add40b4
          - /dev/disk/by-id/wwn-0x5000cca26aea20f7
          - /dev/disk/by-id/wwn-0x5000cca26aea3bf2
          - /dev/disk/by-id/wwn-0x5000cca26cc982cc
    scrub: weekly
    force: true
    properties:
      ashift: 12
    filesystem_properties:
      compression: lz4
      relatime: "on"
      xattr: sa
      utf8only: "on"
    state: present

zfs_datasets:
  spool/iscsi:
    properties:
      dedup: "off"
      compression: "off"
      mountpoint: none
      canmount: noauto
      encryption: "on"
      keyformat: raw
      keylocation: file:///etc/key.d/spool-iscsi.key
    state: present
  spool/iscsi/cantilever:
    properties:
      volsize: 32G
      # @note ansible zfs module doesn't properly strip this for existing
      # datasets. Should be fixed in newer version of ansible once we update
      # the playbooks.
      # volblocksize: 32K
      shareiscsi:
        iqn: iqn.2020-08.net.addeo:kilo:spool-iscsi-cantilever
        options: |
          initiator-address 172.16.0.66
    state: present
  # The main encrypted dataset for most types of data.
  spool/data:
    properties:
      compression: lz4
      # Encryption key is managed by Shavee.
      encryption: "on"
      keyformat: passphrase
      keylocation: prompt
    state: present
  spool/data/backups/proxmox:
    properties:
      sharenfs: "rw=172.16.1.79,anonuid=1001,anongid=1001,no_root_squash,no_subtree_check"
    state: present
  spool/data/downloads:
    state: present
  spool/data/downloads/complete:
    properties:
      sharenfs: "rw=172.16.1.66,anonuid=1001,anongid=1001,no_root_squash,all_squash"
    state: present
  spool/data/downloads/incomplete:
    properties:
      sharenfs: "rw=172.16.1.66,anonuid=1001,anongid=1001,no_root_squash,all_squash"
    state: present
  spool/data/media:
    state: present
  spool/data/media/movies:
    properties:
      sharenfs: "rw=172.16.1.66,anonuid=1001,anongid=1001,no_root_squash,all_squash"
    state: present
  spool/data/media/tv:
    properties:
      sharenfs: "rw=172.16.1.66,anonuid=1001,anongid=1001,no_root_squash,all_squash"
    state: present
  spool/data/timemachines:
    state: present
  spool/data/timemachines/aviato:
    state: present

# Shavee Configuration.
install_shavee: true
shavee_encrypted_datasets:
  - spool-data

# Tmux configuration.
install_tmux: true
# @TODO add some sort of packages__to_merge or something and add `pv` to it
# (and tmux probably, don't really need the role for it)
