---
# Server Configuration.
server_hostname: kilo
server_fqdn: kilo.addeo.net

# Bootstrap Configuration.
bootstrap_zpool_encrypt_root: true
bootstrap_zpool_type: mirror
bootstrap_zpool_disk_identifiers:
  - /dev/disk/by-id/scsi-3500a0751e5a956ff
  - /dev/disk/by-id/scsi-3500a0751e5a9496e

# Network Interfaces Configuration.
network_interfaces:
  eno1:
    auto: true
    no_auto_down: true
    inet: static
    address: 172.16.115.65/31
    state: present
  eno3:
    auto: true
    inet: static
    address: 10.1.15.65/24
    gateway: 10.1.15.1
    dns_nameservers: 10.1.15.1
    state: present

# Firewall Configuration.
kilo_firewall_allowed_udp_ports__to_merge:
  - 137 # SMB
  - 138 # SMB
kilo_firewall_allowed_tcp_ports__to_merge:
  - 139 # SMB
  - 445 # SMB
  - 3260 # iSCSI

# ZFS Configuration.
zfs_pools:
  bpool:
    scrub: false
    state: scrub
  rpool:
    scrub: weekly
    state: scrub
  spool:
    vdevs:
      - type: raidz2
        devices:
          - /dev/disk/by-id/wwn-0x5000cca267c7fe1f
          - /dev/disk/by-id/wwn-0x5000cca267c8344e
          - /dev/disk/by-id/wwn-0x5000cca26add40b4
          - /dev/disk/by-id/wwn-0x5000cca26aea20f7
          - /dev/disk/by-id/wwn-0x5000cca26aea3bf2
          - /dev/disk/by-id/wwn-0x5000cca26cc982cc
    scrub: weekly
    force: true
    properties:
      ashift: 12
    filesystem_properties:
      compression: lz4
      relatime: "on"
      xattr: sa
      utf8only: "on"
    state: present

zfs_datasets:
  # iSCSI datasets need to be outside of spool/data because it's encrypted.
  # Servers booting via iSCSI should encrypt root on their end.
  spool/iscsi:
    properties:
      dedup: off
      compression: off
    state: present
  spool/iscsi/cantilever:
    properties:
      volsize: 100G
      # volblocksize can only be set during creation of the dataset.
      # volblocksize: 32K
      shareiscsi: true
    state: present
  # The main encrypted dataset for most types of data.
  spool/data:
    properties:
      compression: lz4
      # Encryption is enabled, but is manually managed.
      # encryption: true
    state: present

# Shavee Configuration.
install_shavee: true
shavee_encrypted_datasets:
  - spool-data
