---
# Device Information.
device_hostname: klipper
device_description: Klipper
device_type: RaspberryPi
device_model: ~
device_interfaces:
  - ip: 10.1.51.166 # @TODO use static ip, use correct vlan
    mac: ~
    default: true

# DNS Record Configuration.
dns_default_record: true
dns_records:
  - host: fluidd
    domain: addeo.net
    ip: "{{ device_ip }}"
    descr: Fluidd Klipper UI
