---
# Device Information.
device_name: Garage Bridge
device_hostname: loco5ac02
device_type: Unifi airMAX NanoStation 5AC Loco
device_model: Loco5AC
device_vlan: MGMT
device_interfaces:
  - ip: 10.1.10.36
    mac: E0:63:DA:FE:AF:78
    default: true
