---
device_hostname: rtr01
device_description: Core Router
device_type: pfSense Router
device_model: DELL R210ii
device_interfaces:
  - name: bce0
    mac: D4:AE:52:C6:51:10
  - name: bce1
    ip: 10.1.10.1
    mac: D4:AE:52:C6:51:11
    default: true
  - name: idrac
    description: "iDrac Interface (not working)"
    ip: 10.1.10.2
    mac: ~

# DNS Record Configuration.
dns_default_record: false
dns_mgmt_interface: idrac
dns_records:
  - host: "{{ device_hostname }}"
    domain: "{{ dns_domain }}"
    ip: "{{ device_ip }}"
    descr: "{{ device_description }}"
    aliases:
      - host: pfsense
        domain: "{{ dns_domain }}"
        description: "{{ device_description }}"
