---
# Server Configuration.
server_hostname: testbed
server_fqdn: testbed.addeo.net

# Bootstrap Configuration.
bootstrap_zpool_type: mirror
bootstrap_zpool_disk_identifiers:
  - /dev/disk/by-id/ata-VBOX_HARDDISK_VBc3167122-1ef5db5f
  - /dev/disk/by-id/ata-VBOX_HARDDISK_VB8b62a23a-33273c01

# Firewall Configuration.
testbed_firewall_allowed_tcp_ports__to_merge:
  - 3260

# ZFS Configuration.
zfs_pools:
  bpool:
    scrub: false
    state: scrub
  rpool:
    scrub: weekly
    state: scrub
  spool:
    vdevs:
      - type: raidz
        devices:
          - /dev/sdc
          - /dev/sdd
          - /dev/sde
    scrub: weekly
    force: true
    properties:
      ashift: 12
    filesystem_properties:
      compression: lz4
      relatime: "on"
      xattr: sa
      utf8only: "on"
    state: present

zfs_filesystems:
  spool/data:
    properties:
      quota: 50G
      compression: lz4
      sharenfs: false
    state: present
  spool/data/iscsi-test:
    properties:
      volsize: 5M
      shareiscsi: true
    state: present
  spool/data/something:
    state: present
  spool/data/something2:
    properties:
      sharenfs: true
      normalization: formD
    state: present
  spool/data/samba:
    properties:
      sharesmb: true
    state: present
