---
# Server Configuration.
server_hostname: testbed
server_fqdn: testbed.addeo.net

# Bootstrap Configuration.
bootstrap_zpool_type: mirror
bootstrap_zpool_disk_identifiers:
  - /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi0
  - /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1