---
# Server Configuration.
server_hostname: testbed
server_fqdn: testbed.addeo.net

# Bootstrap Configuration.
bootstrap_zpool_type: mirror
bootstrap_zpool_disk_identifiers:
  - /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi0
  - /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1

# Firewall Configuration.
testbed_firewall_allowed_udp_ports__to_merge:
  - 137 # SMB
  - 138 # SMB
testbed_firewall_allowed_tcp_ports__to_merge:
  - 139 # SMB
  - 445 # SMB
  - 3260 # iSCSI

# ZFS Configuration.
zfs_pools:
  bpool:
    scrub: false
    state: scrub
  rpool:
    scrub: weekly
    state: scrub
  spool:
    vdevs:
      - type: raidz
        devices:
          - /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi2
          - /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi3
          - /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi4
    scrub: weekly
    force: true
    properties:
      ashift: 12
    filesystem_properties:
      compression: lz4
      relatime: "on"
      xattr: sa
      utf8only: "on"
    state: present

zfs_datasets:
  spool/iscsi:
    properties:
      quota: 50G
      compression: lz4
      sharenfs: false
    state: present
  spool/iscsi/iscsi-test:
    properties:
      volsize: 5M
      shareiscsi: true
    state: present
  spool/data:
    properties:
      quota: 50G
      compression: lz4
      sharenfs: false
      # Encryption is enabled, but is manually managed.
      # encryption: true
    state: present
  spool/data/something:
    state: present
  spool/data/something2:
    properties:
      sharenfs: true
      normalization: formD
    state: present
  spool/data/samba:
    properties:
      sharesmb: true
    state: present
  spool/data/proxmox:
    state: present

# Shavee Configuration.
install_shavee: true
shavee_use_yubikey: false
shavee_encrypted_datasets:
  - spool-data
