---
# Server Configuration.
server_hostname: violet
server_fqdn: violet.addeo.net

# DNS Record Configuration.
dns_records:
  - host: violet
    domain: addeo.net
    ip: 10.1.15.50
    descr: Portainer Container Server
    aliases:
      - host: pcs01.prd.ado
        domain: addeo.net
        description: pcs01.prd.ado

# Network Interfaces Configuration.
network_interfaces:
  ens18:
    comment: SRVMGMT interface.
    allow: hotplug
    inet: static
    address: 10.1.15.50/24
    gateway: 10.1.15.1
    dns_nameservers: 10.1.15.1
    dns_search: addeo.net
    state: present
  ens22:
    comment: SAN interface.
    auto: true
    inet: static
    address: 10.1.12.50/24
    mtu: 9000
    state: present

# Mount Point Configuration.
mounts:
  - src: 10.1.12.65:/spool/data/media/tv
    path: /data/media/tv
    opts: rsize=8192,wsize=8192,timeo=14,intr
    fstype: nfs
    state: mounted
  - src: 10.1.12.65:/spool/data/media/movies
    path: /data/media/movies
    opts: rsize=8192,wsize=8192,timeo=14,intr
    fstype: nfs
    state: mounted
  - src: 10.1.12.65:/spool/data/downloads/incomplete
    path: /data/downloads/incomplete
    opts: rsize=8192,wsize=8192,timeo=14,intr
    fstype: nfs
    state: mounted
  - src: 10.1.12.65:/spool/data/downloads/complete
    path: /data/downloads/complete
    opts: rsize=8192,wsize=8192,timeo=14,intr
    fstype: nfs
    state: mounted
