---
# Whether or not to install Shavee.
install_shavee: false

# The Shavee tag to download and install.
shavee_tag: v0.5.2

# Whether or not to use YubiKey when decrypting.
shavee_use_yubikey: true

# Which slot on the YubiKey to use.
shavee_yubikey_slot: 1

# ZFS dataset names to be decrypted at boot time via systemd/shavee.
#
# Dataset names should have /'s replaced with -'s for compatability with
# systemd. e.g. spool/data -> spool-data
shavee_encrypted_datasets: []
