---
- name: Ensure Rustup is installed for root
  include_role:
    name: hurricanehrndz.rustup
  vars:
    rustup_user: root

- name: Download Shavee
  unarchive:
    src: "https://github.com/ashuio/shavee/archive/refs/tags/v{{ shavee_tag }}.tar.gz"
    dest: /usr/local/src/
    remote_src: true
    extra_opts:
      - --transform
      - "s/shavee-{{ shavee_tag }}/shavee/"

- name: Install required packages
  apt:
    package:
      - pkg-config
      - libssl-dev
      - libpam0g-dev
    state: present

- name: Build Shavee # noqa: command-instead-of-shell
  shell: ~/.cargo/bin/cargo build --release
  args:
    chdir: /usr/local/src/shavee
    creates: /usr/local/src/shavee/target/release/shavee

- name: Install Shavee binary
  copy:
    src: /usr/local/src/shavee/target/release/shavee
    dest: /usr/local/sbin/shavee
    remote_src: true
    mode: u+rwx,g+rx,o+rx

- name: Ensure /usr/local/lib/security dir exists
  file:
    path: /usr/local/lib/security
    mode: "0755"
    state: directory

- name: Install Shavee PAM module
  copy:
    src: /usr/local/src/shavee/target/release/libshavee_pam.so
    dest: /usr/local/lib/security/libshavee_pam.so
    mode: "0644"
    remote_src: true

- name: Install Shavee systemd unit
  template:
    src: zfs-shavee-unlock@.service.j2
    dest: /etc/systemd/system/zfs-shavee-unlock@.service
    mode: "0644"

- name: Enable Shavee ZFS dataset unlock units
  systemd:
    name: "zfs-shavee-unlock@{{ item }}"
    enabled: true
    state: started
  loop: "{{ shavee_encrypted_datasets }}"
