---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pocket-id
  namespace: pocket-id-system
spec:
  chart:
    spec:
      version: "*"
  values:
    persistence:
      existingClaim: pocket-id-data-pocket-id-0
    ingress:
      host: id.staging.addeo.net
      tls:
        - secretName: pocket-id-tls
          hosts:
            - id.staging.addeo.net
