---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-pocket-id-data-staging
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  csi:
    driver: csi.proxmox.sinextra.dev
    fsType: xfs
    volumeAttributes:
      storage: vmpool
    volumeHandle: armada/crimson/vmpool/vm-9999-pvc-pocket-id-data-staging
  storageClassName: vmpool-persistent
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pocket-id-data
  namespace: pocket-id-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: vmpool-persistent
  volumeName: pvc-pocket-id-data-staging
