apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  releaseName: rancher
  chart:
    spec:
      chart: rancher
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: rancher
  interval: 12h
  # Default values
  # https://github.com/rancher/rancher/blob/release/v2.8/chart/values.yaml
  values:
    ingress:
      ingressClassName: nginx
      tls:
        source: secret
      extraAnnotations:
        cert-manager.io/cluster-issuer: letsencrypt
