---
apiVersion: v1
kind: Secret
metadata:
  name: proxmox-cluster
  namespace: kube-system
type: Opaque
stringData:
  config.yaml: |
    clusters:
      - url: https://cantilever.addeo.net:8006/api2/json
        insecure: true
        token_id: {{ op://k8s/e33vetsc55hia7detdukuvryya/username }}
        token_secret: {{ op://k8s/e33vetsc55hia7detdukuvryya/credential }}
        region: armada
---
apiVersion: v1
kind: Namespace
metadata:
  name: op-system
---
apiVersion: v1
kind: Secret
metadata:
  name: op-credentials
  namespace: op-system
type: Opaque
stringData:
  1password-credentials.json: |
    {{ op://Infrastructure/Production Credentials File/1password-credentials.json }}
---
apiVersion: v1
kind: Secret
metadata:
  name: onepassword-token
  namespace: op-system
type: Opaque
stringData:
  token: "{{ op://Infrastructure/x35elwai2jgploujunynk6bt3y/credential }}"
