---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pocket-id-system
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
replacements:
  - source:
      kind: Secret
      name: pocket-id-maxmind-license-key
      namespace: pocket-id-system
      fieldPath: data.credential
    targets:
      - select:
          name: pocket-id
          kind: HelmRelease
        fieldPaths:
          - spec.values.maxmindLicenseKey
