---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pocket-id
  namespace: pocket-id-system
spec:
  releaseName: pocket-id
  chart:
    spec:
      chart: pocket-id
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: anza-labs
  interval: 12h
  # Default values
  # https://github.com/anza-labs/charts/blob/main/charts/pocket-id/values.yaml
  values:
    timeZone: "America/New_York"
    maxmindLicenseKey: "REDACTED"
    persistence:
      data:
        enabled: true
        storageClass: vmpool
    ingress:
      enabled: true
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/configuration-snippet: |
          proxy_busy_buffers_size 512k;
          proxy_buffers 4 512k;
          proxy_buffer_size 256k;
