---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pocket-id
  namespace: pocket-id-system
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  releaseName: pocket-id
  chart:
    spec:
      chart: pocket-id
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: anza-labs
  interval: 12h
  # Default values
  # https://github.com/anza-labs/charts/blob/main/charts/pocket-id/values.yaml
  values:
    timeZone: "America/New_York"
    maxmindLicenseKey: "${POCKET_ID_MAXMIND_LICENSE_KEY:=}"
    persistence:
      data:
        enabled: true
        storageClass: vmpool
    ingress:
      enabled: true
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/proxy-busy-buffers-size: "512k"
        nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
        nginx.ingress.kubernetes.io/proxy-buffer-size: "256k"
