---
- hosts: proxmox_backup_servers
  become: true
  tasks:
    - name: Install curl
      apt:
        name: curl
        state: present

    - name: Add Proxmox GPG key
      command: curl https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg -o /etc/apt/trusted.gpg.d/proxmox-release-bookworm.gpg
      args:
        creates: /etc/apt/trusted.gpg.d/proxmox-release-bookworm.gpg

    - name: Empty the /etc/apt/sources.list file
      copy:
        content: "# File intentionally left blank."
        dest: /etc/apt/sources.list

    - name: Add apt repositories
      apt_repository:
        repo: "{{ item }}"
        update_cache: false
        state: present
      loop:
        - deb http://deb.debian.org/debian bookworm main contrib non-free-firmware
        - deb-src http://deb.debian.org/debian bookworm main contrib non-free-firmware
        - deb http://deb.debian.org/debian bookworm-updates main contrib non-free-firmware
        - deb-src http://deb.debian.org/debian bookworm-updates main contrib non-free-firmware
        - deb http://security.debian.org/debian-security bookworm-security main contrib non-free-firmware
        - deb-src http://security.debian.org/debian-security bookworm-security main contrib non-free-firmware
        - deb http://download.proxmox.com/debian/pbs bookworm pbs-no-subscription

    - name: Remove enterprise Proxmox repository
      apt_repository:
        repo: "deb https://enterprise.proxmox.com/debian/pbs bookworm pbs-enterprise"
        update_cache: true
        state: absent

    - name: Install Proxmox Backup Server
      apt:
        name: proxmox-backup
        update_cache: true
        state: present

    - name: Remove subscription nag message
      lineinfile:
        path: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
        line: "        orig_cmd(); return;"
        insertafter: '^\s+checked_command: function\(orig_cmd\) {$'
        firstmatch: true
        backup: true

    - set_fact:
        pbs_root_password: "{{ pbs_root_password }}"
      no_log: true

    - name: Update root user password
      user:
        name: root
        password: "{{ pbs_root_password | password_hash('sha512', 65535 | random(seed=inventory_hostname) | string) }}"
      no_log: true
