---
collections:
  - name: community.general
    version: 3.7.0
    source: https://galaxy.ansible.com

  - name: devsec.hardening
    version: 7.12.0
    source: https://galaxy.ansible.com

roles:
  - name: geerlingguy.ntp
    version: 2.3.0

  - name: hurricanehrndz.rustup

  - name: geerlingguy.firewall
    version: 2.5.0

  - name: oefenweb.fail2ban
    version: v3.4.1

  - name: oefenweb.postfix
    version: v3.5.1

  - name: hifis.unattended_upgrades
    version: v3.2.1

  - name: maxhoesel.nut_netclient

  - name: lae.proxmox
    src: https://github.com/lae/ansible-role-proxmox
    version: v1.9.1

  - name: andrewrothstein.tmux
    version: v1.0.7
