---
- hosts: servers
  become: true
  collections:
    - devsec.hardening
  pre_tasks:
    - name: Merge firewall_allowed_tcp_ports
      merge_vars:
        suffix_to_merge: firewall_allowed_tcp_ports__to_merge
        merged_var_name: firewall_allowed_tcp_ports
        expected_type: list
      tags: firewall

    - name: Merge firewall_allowed_udp_ports
      merge_vars:
        suffix_to_merge: firewall_allowed_udp_ports__to_merge
        merged_var_name: firewall_allowed_udp_ports
        expected_type: list
      tags: firewall

    - name: Merge server_users
      merge_vars:
        suffix_to_merge: server_users__to_merge
        merged_var_name: server_users
        expected_type: list
      tags: users
  roles:
    - geerlingguy.ntp

    - role: os_hardening
      when: harden_server is defined and harden_server

    - role: ssh_hardening
      when: harden_server is defined and harden_server

    - role: oefenweb.fail2ban
      when: harden_server is defined and harden_server

    # @bug: my dell-omsa role no longer works with Debian 12, and OMSA is
    # deprecated now. May need to use iSM instead.
    # - role: dell-omsa
    #   when: install_dell_omsa is defined and install_dell_omsa

    - role: plymouth
      when: install_plymouth is defined and install_plymouth
      tags: plymouth

    - role: geerlingguy.firewall
      when: manage_firewall is defined and manage_firewall
      tags: firewall

    - role: oefenweb.postfix
      when: install_postfix is defined and install_postfix

    - role: jnv.unattended-upgrades
      when: manage_unattended_upgrades is defined and manage_unattended_upgrades

    - role: maxhoesel.nut_netclient
      when: install_nut is defined and install_nut

    - role: shavee
      when: install_shavee is defined and install_shavee
      tags: shavee

    - role: zfs
      when: manage_zfs is defined and manage_zfs
      tags: zfs

    - role: network-interfaces
      when: manage_network_interfaces is defined and manage_network_interfaces
      tags: network-interfaces

    - role: andrewrothstein.tmux
      when: install_tmux is defined and install_tmux
      tags: tmux
  tasks:
    - name: Ensure ZFS snapshots are taken before unattended upgrades are performed
      when: (manage_zfs is defined and manage_zfs) and (manage_unattended_upgrades is defined and manage_unattended_upgrades)
      blockinfile:
        path: /usr/lib/apt/apt.systemd.daily
        insertbefore: "# auto upgrade all upgradeable packages"
        block: |
          # Take snapshots before running unattended upgrades.
          zfs snapshot rpool/root/debian@unattended-$(date +%s)
          zfs snapshot bpool/boot/debian@unattended-$(date +%s)
          # Clean up old snapshots, keeping the 3 most recent.
          zfs list -t snapshot -o name -S creation | grep ^rpool/root/debian@unattended | tail -n +4 | xargs -r -n 1 zfs destroy -vr
          zfs list -t snapshot -o name -S creation | grep ^bpool/boot/debian@unattended | tail -n +4 | xargs -r -n 1 zfs destroy -vr

    - name: Ensure user home directory zfs datasets exist
      zfs:
        name: "rpool/home/{{ item.name }}"
        state: present
      loop: "{{ server_users }}"
      when: (manage_zfs is defined and manage_zfs) and (item.create_home is not defined or item.create_home)
      no_log: true
      tags: users

    - name: Ensure users exist
      user:
        name: "{{ item.name }}"
        groups: "{{ item.groups | default(omit) }}"
        password: "{{ (item.password is defined) | ternary(item.password | default(omit) | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string), '!') }}"
        shell: "{{ item.shell | default('/bin/bash') }}"
        password_lock: "{{ item.password_lock | default(false) }}"
        create_home: "{{ item.create_home | default(true) }}"
        append: true
      loop: "{{ server_users }}"
      no_log: true
      tags: users

    - name: Check if user home directories have been skeletonized
      stat:
        path: "/home/{{ item.name }}/.profile"
      register: server_users_stat
      loop: "{{ server_users }}"
      no_log: true
      tags: users

    - name: Ensure user home directories have been skeletonized
      copy:
        src: /etc/skel/.
        dest: "/home/{{ item.0.name }}/."
        owner: "{{ item.0.name }}"
        group: "{{ item.0.name }}"
        remote_src: true
        force: "{{ not item.1.stat.exists }}"
      loop: "{{ server_users | zip(server_users_stat.results) | list }}"
      when: item.0.create_home is not defined or item.0.create_home
      no_log: true
      tags: users

    - name: Ensure user home directories have the correct ownership
      file:
        path: "/home/{{ item.name }}"
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
        state: directory
      loop: "{{ server_users }}"
      when: item.create_home is not defined or item.create_home
      no_log: true
      tags: users

    - name: Ensure users ssh keys have been added to authorized_keys
      authorized_key:
        user: "{{ item.name }}"
        key: "{{ lookup('file', item.ssh_public_key_file) }}"
        state: present
      loop: "{{ server_users }}"
      when: item.ssh_public_key_file is defined and (item.create_home is not defined or item.create_home)
      no_log: true
      tags: users

    - name: Ensure the sudo group allows passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        regexp: "^%sudo   ALL=(ALL:ALL) ALL$"
        line: "%sudo   ALL=(ALL:ALL) NOPASSWD: ALL"

    - name: Ensure the server hostname is set
      copy:
        dest: /etc/hostname
        content: "{{ server_hostname }}\n"
      when: manage_hostname is defined and manage_hostname

    - name: Ensure the servers hostname/fqdn are in /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: |
          {% if server_fqdn != '' -%}
            {{ ansible_default_ipv4.address }}       {{ server_fqdn }} {{ server_hostname }}
          {% else -%}
            127.0.1.1       {{ server_hostname }}
          {% endif %}
        line: |
          {% if server_fqdn != '' -%}
            {{ ansible_default_ipv4.address }}       {{ server_fqdn }} {{ server_hostname }}
          {% else -%}
            127.0.1.1       {{ server_hostname }}
          {% endif %}
      when: manage_hostname is defined and manage_hostname

    - set_fact:
        has_nfs_mounts: "{{ mounts | json_query('[?fstype == `nfs`]') | length > 0 }}"
      when: manage_mounts is defined and manage_mounts
      tags: mounts

    - name: Ensure nfs-common is installed if there are nfs mounts
      apt:
        name: nfs-common
        update_cache: true
        state: present
      when: (manage_mounts is defined and manage_mounts) and has_nfs_mounts
      tags: mounts

    - name: Ensure mount points are configured
      mount: "{{ item }}"
      loop: "{{ mounts }}"
      when: manage_mounts is defined and manage_mounts
      tags: mounts
