---
- hosts: servers
  become: true
  collections:
    - devsec.hardening
  roles:
    - os_hardening
    - ssh_hardening
    - oefenweb.fail2ban
    - dell-omsa
    - plymouth
    - geerlingguy.firewall
    - geerlingguy.ntp
