apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pocket-id
  namespace: pocket-id-system
spec:
  chart:
    spec:
      version: "*"
  values:
    ingress:
      host: rancher.staging.addeo.net
