apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  chart:
    spec:
      version: "*"
  values:
    hostname: rancher.staging.addeo.net
