---
# Ansible Configuration.
ansible_user: ansible
ansible_ssh_private_key_file: "{{ inventory_dir }}/host_keys/id_rsa.ansible@addeo.net"
ansible_python_interpreter: /usr/bin/python3

# NTP Configuration.
ntp_timezone: America/New_York
ntp_package: chrony
ntp_daemon: chronyd
ntp_config_file: /etc/chrony.conf
