---
apiVersion: v1
kind: Namespace
metadata:
  name: nfs-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nfs-subdir-external-provisioner
  namespace: nfs-system
spec:
  interval: 24h
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: nfs-system
spec:
  interval: 30m
  releaseName: nfs-subdir-external-provisioner
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
  # https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/blob/master/charts/nfs-subdir-external-provisioner/values.yaml
  values:
    nfs:
      server: kilo.san.addeo.net
      path: /spool/data/k8s/staging
      mountOptions:
        - vers=4.1
