---
apiVersion: v1
kind: Namespace
metadata:
  name: proxmox-csi-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: proxmox-csi-token
  namespace: proxmox-csi-system
spec:
  itemPath: vaults/k8s/items/kubernetes-csi@pve
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: proxmox-csi
  namespace: proxmox-csi-system
spec:
  interval: 24h
  url: oci://ghcr.io/sergelogvinov/charts/proxmox-csi-plugin
  ref:
    semver: "*"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: proxmox-csi
  namespace: proxmox-csi-system
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: proxmox-csi
    namespace: proxmox-csi-system
  values:
    config:
      clusters:
        - url: https://cantilever.addeo.net:8006/api2/json
          insecure: true
          # @TODO !provider should be !csi, need to make new tokens (and for tofu)
          token_id: kubernetes-csi@pve!provider
          region: armada
  valuesFrom:
    - kind: Secret
      name: proxmox-csi-token
      valuesKey: credential
      targetPath: config.clusters[0].token_secret
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: vmpool
parameters:
  csi.storage.k8s.io/fstype: xfs
  storage: vmpool
  cache: writethrough
  ssd: "true"
mountOptions:
  - noatime
provisioner: csi.proxmox.sinextra.dev
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
