---
apiVersion: v1
kind: Namespace
metadata:
  name: proxmox-csi-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: proxmox-csi
  namespace: proxmox-csi-system
spec:
  interval: 24h
  url: oci://ghcr.io/sergelogvinov/charts/proxmox-csi-plugin
  ref:
    semver: "*"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: proxmox-csi
  namespace: proxmox-csi-system
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: proxmox-csi
    namespace: proxmox-csi-system
  values:
    config:
      clusters:
        - url: https://cantilever.addeo.net:8006/api2/json
          insecure: true
          token_id: kubernetes-csi!provider
          token_secret: "${PROXMOX_CSI_TOKEN}"
          region: armada
