---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: proxmox-ccm-token
  namespace: kube-system
spec:
  itemPath: vaults/k8s/items/kubernetes-csi@pve
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: proxmox-cloud-controller-manager
  namespace: kube-system
spec:
  interval: 24h
  url: oci://ghcr.io/sergelogvinov/charts/proxmox-cloud-controller-manager
  ref:
    semver: "*"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: proxmox-cloud-controller-manager
  namespace: kube-system
spec:
  dependsOn:
    - name: 1password
      namespace: op-system
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: proxmox-cloud-controller-manager
    namespace: kube-system
  values:
    config:
      clusters:
        - url: https://cantilever.addeo.net:8006/api2/json
          insecure: true
          token_id: kubernetes-csi@pve!provider
          region: armada
  valuesFrom:
    - kind: Secret
      name: proxmox-ccm-token
      valuesKey: credential
      targetPath: config.clusters[0].token_secret
